[tasks.rebuild]
command = "doas"
args = ["nixos-rebuild", "switch", "--flake", "."]

[tasks.boot]
command = "doas"
args = ["nixos-rebuild", "boot", "--flake", "."]

[tasks.update]
command = "nix"
args = ["flake", "update"]

[tasks.gc]
dependencies = [
    "clean-system",
    "clean-home"
]

[tasks.gc-system]
command = "doas"
args = ["nix", "store", "gc"]

[tasks.gc-home]
command = "nix"
args = ["store", "gc"]

[tasks.playground]
command = "nix"
args = ["develop", ".#playground"]
