[theme]
theme = "iceberg"

[icons]
icons = "none"

[[block]]
block = "keyboard_layout"
driver = "sway"
[block.mappings]
"English (US)" = "US"
"Swedish (N/A)" = "SE"

[[block]]
block = "hueshift"
hue_shifter = "gammastep"
min_temp = 2000
max_temp = 6500
click_temp = 5000
step = 500

[[block]]
block = "backlight"
if_command = "test -e /sys/class/backlight/*backlight/"
minimum = 5
maximum = 100
step_width = 5
cycle = [100, 50, 5, 50]

[[block]]
block = "sound"
headphones_indicator = true
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "net"
format = " $ip "
format_alt = " $ssid ($signal_strength) "
missing_format = " NA "
interval = 10

[[block]]
block = "battery"
device = "BAT0"
if_command = "test -e /sys/class/power_supply/BAT0"
missing_format = ""
good = 75
warning = 50
critical = 25
interval = 10

[[block]]
block = "time"
interval = 10
format = " $timestamp.datetime(f:'%Y-%m-%d %R') "
icons_format = " "
